Task23BugLess/Models/BlogModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Task23BugLess.Models
{
    public class BlogModel
    {
        public int Id { get; set; }
        public string Header { get; set; }
        public string Content{ get; set; }
        public string AuthorName { get; set; }
        public DateTime CreationTime { get; set; }
    }
}

Task23BugLess/Models/FeedbackModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Task23BugLess.Models
{
    public class FeedbackModel
    {
        public string AuthorName { get; set; }
        public DateTime CreationTime { get; set; }
        public string Content { get; set; }
        public int BlogId { get; set; }

        public FeedbackModel(int blogId, string authorName, DateTime time, string content)
        {
            BlogId = blogId;
            AuthorName = authorName;
            CreationTime = time;
            Content = content;
        }
    }
}

Task23BugLess/Controllers/GuestController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task23BugLess.Models;

namespace Task23.Controllers
{
    public class GuestController : Controller
    {
        private static List<FeedbackModel> _feedbacks;
        static GuestController() 
        {
            _feedbacks = new List<FeedbackModel>()
            {
                new FeedbackModel(0, "megakiller_2009", DateTime.Now, "Hello"),
                new FeedbackModel(0, "1223", DateTime.Now, "Бобало геній"),
                new FeedbackModel (0, "naruto@ss@in", DateTime.Now, "люблю доту"),
                new FeedbackModel(0, "test", DateTime.Now, "завтра в школу"),
                new FeedbackModel(0, "megakiller_2009", DateTime.Now, "Hello"),

                new FeedbackModel(1, "Nazar", DateTime.Now, "Green bottle blue"),
                new FeedbackModel (1, "Math", DateTime.Now, "люблю math"),
                new FeedbackModel(1, "testik111", DateTime.Now, "рівне макдональдс"),
                new FeedbackModel(1, "megakiller_2009", DateTime.Now, "Hello"),
                
                new FeedbackModel(2, "1223", DateTime.Now, "Бобало геній"),
                new FeedbackModel (2, "naruto@ss@in", DateTime.Now, "люблю доту"),
                
                new FeedbackModel (3, "naruto@ss@in", DateTime.Now, "люблю доту"),

                new FeedbackModel(4, "megakiller_2009", DateTime.Now, "Hello"),
                new FeedbackModel(4, "1223", DateTime.Now, "Бобало геній")
                
                //new FeedbackModel (5, "naruto@ss@in", DateTime.Now, "люблю доту"),
                //new FeedbackModel(5, "test", DateTime.Now, "завтра в школу"),
                //new FeedbackModel(5, "megakiller_2009", DateTime.Now, "Hello"),
                //new FeedbackModel(5, "1223", DateTime.Now, "Бобало геній"),
                //new FeedbackModel (6, "naruto@ss@in", DateTime.Now, "люблю доту"),
                //new FeedbackModel(6, "test", DateTime.Now, "завтра в школу"),
            };
        }
        public ActionResult Index()
        {
            return View(_feedbacks);
        }
        [HttpGet]
        public ActionResult Feedback(int id)
        {
            var blogFeedback = _feedbacks.Where(feedback => feedback.BlogId == id);
            return View(blogFeedback);
        }
    }
}

Task23BugLess/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task23BugLess.Models;

namespace Task23.Controllers
{
    public class HomeController : Controller
    {
        private static Collection<BlogModel> _blogs;
        private static int AutoIncrement { get { return _autoIncrement++; } }
        private static int _autoIncrement;

        static HomeController()
        {
            _blogs = new Collection<BlogModel>()
            {
                new BlogModel()
                {
                    Id = AutoIncrement,
                    Header =  "Getting started",
                    Content = "ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that enables a clean separation of concerns and gives you full control over markup for enjoyable, agile development.",
                    AuthorName = "James",
                    CreationTime = DateTime.Parse("4/22/2021 12:38:31 AM")
                },
                 new BlogModel()
                {
                    Id = AutoIncrement,
                    Header =  "Getting started",
                    Content = "ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that enables a clean separation of concerns and gives you full control over markup for enjoyable, agile development.",
                    AuthorName = "James",
                    CreationTime = DateTime.Parse("4/22/2021 12:38:31 AM")
                },
                  new BlogModel()
                {
                    Id = AutoIncrement,
                    Header =  "Getting started",
                    Content = "ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that enables a clean separation of concerns and gives you full control over markup for enjoyable, agile development.",
                    AuthorName = "James",
                    CreationTime = DateTime.Parse("4/22/2021 12:38:31 AM")
                },
                   new BlogModel()
                {
                    Id = AutoIncrement,
                    Header =  "Getting started",
                    Content = "ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that enables a clean separation of concerns and gives you full control over markup for enjoyable, agile development.",
                    AuthorName = "James",
                    CreationTime = DateTime.Parse("4/22/2021 12:38:31 AM")
                }, new BlogModel()
                {
                    Id = AutoIncrement,
                    Header =  "Getting started",
                    Content = "ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that enables a clean separation of concerns and gives you full control over markup for enjoyable, agile development.",
                    AuthorName = "James",
                    CreationTime = DateTime.Parse("4/22/2021 12:38:31 AM")
                }
            };
        }
        public ActionResult Index()
        {
            return View(_blogs);
        }

    }
}

Task23BugLess/Views/Guest/Feedback.cshtml
@model System.Collections.Generic.IEnumerable<Task23BugLess.Models.FeedbackModel>

<div class="feedback-container">
    @foreach (var feedback in Model) 
    {
        <div class="feedback">
            <h2>@feedback.Content</h2>
            <b><i>Author: @feedback.AuthorName</i></b>
            <h5>Date: @feedback.CreationTime</h5>
            <h5>Id: @feedback.BlogId</h5>
        </div>
    }
</div>
<div class="feedback-form">
    @using (Html.BeginForm("Feedback", "Guest", FormMethod.Post))
    {
        <label for="feedback-content-author-name">Enter author name: </label><input type="text" id="feedback-content-author-name" />
        <label for="feedback-content">Enter feedback text: </label><input type="text" id="feedback-content" />
        <input type="submit" value="send"/>
    }
</div>


Task23BugLess/Views/Guest/Index.cshtml
@model System.Collections.ObjectModel.Collection<Task23BugLess.Models.FeedbackModel>
@{
    ViewBag.Title = "Index";
}

    <div class="feedback-container">
        @foreach (var feedback in Model)
        {
            <div class="feedback">
                <h2>@feedback.Content</h2>
                <b><i>Author: @feedback.AuthorName</i></b>
                <h5>Date: @feedback.CreationTime</h5>
                <h3>@feedback.BlogId</h3>
            </div>
        }
    </div>

Task23BugLess/Views/Home/Index.cshtml
@model System.Collections.ObjectModel.Collection<Task23BugLess.Models.BlogModel>

<div>
    @foreach(var blog in Model) 
    {
        <div class="blog">
            <h2>@blog.Header</h2>
            <p>
                @blog.Content
            </p>
            <b><i>Author: @blog.AuthorName</i></b>
            <h5>Date: @blog.CreationTime</h5>
            @Html.ActionLink("See comments", "Feedback", "Guest", new { id = blog.Id }, new {@class = "blog-link" })
        </div>
    }

</div>

Task23BugLess/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header main">

                <a href="/" class="navbar-brand"><i class="fa fa-fw fa-book"></i>Library</a>
                @*@Html.ActionLink("Library", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="row">
            <div class="col-md-9">
                @RenderBody()

            </div>
            <div class="col-md-3">
                <div class="jumbotron">
                    <ul class="jumbotron-menu">
                        <li>
                            @Html.ActionLink("Main", "Index", "Home", new { area = "" }, new { @class = "jumbotron-menu-item" })
                        </li>
                        <li>
                            @Html.ActionLink("Guest", "Index", "Guest", new { area = "" }, new { @class = "jumbotron-menu-item" })
                        </li>
                        <li>
                            @Html.ActionLink("Questionnaire", "Index", "Home", new { area = "" }, new { @class = "jumbotron-menu-item" })
                        </li>
                    </ul>
                </div>

            </div>
        </div>

        <hr />
        <footer class="navbar-fixed-bottom">
            <div class="container">
                <p>&copy; Yevhenii Hrytsiuk topkokos1337@gmail.com - My ASP.NET Application</p>
            </div>
        </footer>

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</body>
</html>